$(document).ready(function () {
    const path = $('#ctxPath').val()
    const element = document.getElementById('list')
    let nome2 = $('#nome2')
    let descrizione2 = $('#descrizione2')
    let marchio2 = $('#marchio2')
    let prezzo2 = $('#prezzo2')
    let sconto2 = $('#sconto2')
    let peso2 = $('#peso2')
    let productId = $('#product-id')
    let cat = $('#fieldProductCategry')
    let file = $('#feldImage')
    $('#list').bind('change', function () {
        const id = element.options[element.selectedIndex].text
        console.log(id)
        $.post(path + '/controlpanel/get', {productId: id}, function (data) {
            console.log(data)
            productId.val(id)
            nome2.val(data.Nome)
            descrizione2.val(data.Descrizione)
            marchio2.val(data.Marchio)
            prezzo2.val(data.Prezzo)
            sconto2.val(data.Sconto)
            cat.val(data.Categoria)
            peso2.val(data.Peso)
        })
    })
})